### ISSUE TITLE
Please update the Documentation so that people won't keep asking the same question

### ISSUE THREAD

**Issue by yaohongkok** [Mila432/Pokemon_Go_API#101]
I realized why people are all asking the same question. The problem is the doc is written in a way that makes people believe you have released the full API.

I can understand why you would hesitate to release the API. 

But, if you can just update the documentation to clearly state that this API is NOT FULLY USABLE, that would be great. I am a watcher of this API and I just keep getting spammed by people who don't even bother to read the code or test it out.

Thanks!

**Comment by Mila432** [comment]
@yaohongkok sorry for this ! will turn off issues now 👍
