### ISSUE TITLE
diable google login?

### ISSUE THREAD

**Issue by mich3lam** [Mila432/Pokemon_Go_API#11]
im trying to use ptc, i didnt put any info to google and it keeps saying this:
http://i.imgur.com/Wsm2gsR.png
why? :c

**Comment by Mila432** [comment]
@mich3lam please change this line to False
https://github.com/Mila432/Pokemon_Go_API/blob/master/config.py#L16

**Comment by mich3lam** [comment]
ok thanks. last question i promise xd
where do i get a login token ? :)

**Comment by Mila432** [comment]
login token comes either from google or pokemon trainer site which is down for 2 days now ..

**Comment by mich3lam** [comment]
ah, so it generates it automatically?

**Comment by Mila432** [comment]
@mich3lam yes

**Comment by mich3lam** [comment]
thank you so much mika! you are great! :)
