### ISSUE TITLE
stops.py and logic.py

### ISSUE THREAD

**Issue by erhan-** [Mila432/Pokemon_Go_API#12]
Nice progress Mila! Will you make stops.py and your logic.py also public or are you just testing stuff for yourself? 
Thanks for the effort. You are number one at the moment with this stuff. You should write a blog post or something for yourself.

Edit: Sorry didn't refresh the Issue overview before posting.

**Comment by Nostrademous** [comment]
Seems Mila is leveraging some of tejado's work (which she acknowledges). 

Tejado doesn't have Google Login integrated, Mila does. Tejado did have ability to spoof location coordinates which Mila has added in the public.py (basically Tejado's "main.py"). 

Mila is probably working on leveraging that to create a "pathing AI" that takes a starting location and an ending location and with some noise inserted, to prevent a rigid pathing track record, Mila will setup intermediary spoofed locations that walk from A -> B (at no more than allowed max speed). 

Mila, I'm willing to help you with this as I just go into Pokemon Go and just started reversing the packet formats (and proto formats). Ran into your work (and tejado) and am leveraging and coming up to speed on what is done so I don't have to start from scratch. Your call, message me if you want help. I could work on building a pokestop path (based on ground truth in my area) while you work on Pathing AI, or vice versa... or I can start looking at parsing pokemon interaction/capture packets.

**Comment by Mila432** [comment]
@Nostrademous i only included tejado's because it uses the public proto file and will allow the public part of mine to work with it , things like faking location are not used here, its only included to work with the google login
