### ISSUE TITLE
No module named google.protobuf

### ISSUE THREAD

**Issue by VonSidia** [Mila432/Pokemon_Go_API#13]
Having bit of a problem if anyone can help me solve this. 

Traceback (most recent call last):
  File "C:\VO\pokemon\main.py", line 10, in <module>
    import public
  File "C:\VO\pokemon\public.py", line 6, in <module>
    import public_proto_pb2
  File "C:\VO\pokemon\public_proto_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf

**Comment by Mila432** [comment]
pip install protobuf or easy_install protobuf

**Comment by VonSidia** [comment]
I tried pip install, didn't seem to work. I'll try easy_install though.

**Comment by erhan-** [comment]
Try pip2.7 install protobuf

**Comment by erhan-** [comment]
Most setups use python 3 as default but we use python2.7 here.

**Comment by VonSidia** [comment]
I've been using Python 2.7 and installed protobuf with both pip and easy_install. Hasn't made any different. Which is making the me stumped on this process. :/

**Comment by Nostrademous** [comment]
Is your PYTHON_PATH set to include site-libs?

**Comment by VonSidia** [comment]
I solved it, but thanks for your help guys. Some googling did the trick, lol.

**Comment by erhan-** [comment]
You should post your solution for others, too.
