### ISSUE TITLE
On problems getting google token

### ISSUE THREAD

**Issue by erhan-** [Mila432/Pokemon_Go_API#14]
A small hint:

google sometimes tries to block the login if you use a proxy and also because of the different user agent. If anyone has problems like me, try to log in to google with that same IP address with your normal browser. Then google will show you that there was a blocked login attempt and you can choose to allow attempts from that devices / ip in future.

**Comment by Mila432** [comment]
i am aware of this 
@erhan- for this change the user agent to one you normally are using and do the steps you mentioned

**Comment by c133** [comment]
Hi, I am receiving an error: [https://i.imgur.com/4OmlPKB.png](url)

I am passing in a gmail address as username along with the password, is this a user agent problem, or is it because the Niantic servers are down?

**Comment by Mila432** [comment]
@c133 you are using ptc as login not google change https://github.com/Mila432/Pokemon_Go_API/blob/master/config.py#L16 to True

**Comment by c133** [comment]
Thank you @Mila432 

I am using only files located here: [https://github.com/dakk/pokemongo-api-demo](https://github.com/dakk/pokemongo-api-demo)
This is using your google auth.

Since there is no config.py being used, I cannot change the value to true. This is with the location feature added by @leegao [https://github.com/leegao/pokemongo-api-demo/tree/simulation](https://github.com/leegao/pokemongo-api-demo/tree/simulation)

Which repo should I be using for the location feature?

Thank you for your time.

**Comment by Mila432** [comment]
@c133 use the file like this :
python script_name.py -g

**Comment by c133** [comment]
`[+] Authentication with google...
SNIMissingWarning
InsecurePlatformWarning
Traceback (most recent call last):
  File "/storage/emulated/0/com.hipipal.qpyplus/scripts/main.py", line 314, in <module>
    main()
  File "/storage/emulated/0/com.hipipal.qpyplus/scripts/main.py", line 275, in main
    access_token = login_google(args.username, args.password)
  File "/storage/emulated/0/com.hipipal.qpyplus/scripts/main.py", line 182, in login_google
    fourth= r2.history[1].headers['Location'].replace('amp%3B','')
IndexError: list index out of range
1|u0_a264@hero2lte:/ $`

Thanks @Mila432, I am now getting an error with the access_token, list index out of range. Do I need to change user agent now?

**Comment by c133** [comment]
Or is this because QPython didn't compile the SSL stuff in?

**Comment by Mila432** [comment]
@c133 use this changes to fix it https://github.com/Mila432/Pokemon_Go_API/commit/d860fdd8c2ee1b5fff9eb0cb0235426c7c34a491

**Comment by Mila432** [comment]
@erhan- please try https://github.com/Mila432/Pokemon_Go_API/commit/598ece06b1c5bd9b753e0e5573aa1d76970386c9
