### ISSUE TITLE
get_profile

### ISSUE THREAD

**Issue by Nostrademous** [Mila432/Pokemon_Go_API#15]
Servers are up:

[!] Using google as login..
[+] Token: <TOKEN>...
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/20/rpc
[-] error in get_profile
[-] Ooops...

Will work on this next... kid woke up from nap, no time now.

**Comment by erhan-** [comment]
I don't have this problem but I had to fix some minor bugs like missing ltype or datetime. 

[+] Login successful
[+] Username: *
[+] You are playing Pokemon Go since: 2016-07-08 00:00:00
[+] Poke Storage: *
[+] Item Storage: *
[+] POKECOIN: *
[+] STARDUST: *
