### ISSUE TITLE
access_token bad

### ISSUE THREAD

**Issue by devian223** [Mila432/Pokemon_Go_API#18]
I'm constantly getting 
"pokemon attacking the login server"
followed by
"access_token bad"

The servers are back up. No mistake in login and pwd, google flag set to false.

PTC login works without any problems in the app.

**Comment by dmadisetti** [comment]
Have you logged in on a phone yet? I'm fairly sure the servers have to create your player before you can properly authenticate

**Comment by Mila432** [comment]
"pokemon attacking the login server" -> the login server for ptc are offline for 2 days now

**Comment by devian223** [comment]
Do you have any plans of giving some "hints" how you programmed the bot the showed in the YT vid? I'm not expecting you to give us the got (at least not publicly), but any guidance would be great. I'm an advanced programmer and into reverse engineering myself, just like to learn more about this.

**Comment by kkatayama** [comment]
I have logged in using your tool. How do I load the Pokestop bot?

**Comment by xau1** [comment]
I'm having similar issue with access_token bad:

C:\poke>main.py
[!] Using google as login..
[-] problem in google login..
[-] access_token bad

**Comment by Mila432** [comment]
i will try to add some debug info tomorrow

**Comment by Taranis01** [comment]
@xau1 could it be that your first account is using 2-factor authentification while the second isnt?

**Comment by Mila432** [comment]
@xau1 please try https://github.com/Mila432/Pokemon_Go_API/commit/598ece06b1c5bd9b753e0e5573aa1d76970386c9

**Comment by iHydra** [comment]
[!] Using google as login..
[-] problem in google login..
[-] access_token bad

Getting this error on a 2FA Google account but I am using the App Password that gets generated here: https://security.google.com/settings/security/apppasswords

Any idea on how to resolve this?

**Comment by Mila432** [comment]
@iHydra I have to try this with an 2FA account and update the code

**Comment by devian223** [comment]
I see you made changes to login.py for PTC accounts, but it still doesn't work

**Comment by mikeres0** [comment]
+1 for this. I'll look around in the code and see what's going on.. I'll try and add some debugging into my local copy and report back.

**Comment by stealthhex** [comment]
Set the  use_proxy=False instead of True and it works =)

**Comment by mikeres0** [comment]
@stealthhex I've looked for this in the main.py but I can't find the syntax `use_proxy=False` anywhere other than the config.py

**Comment by stealthhex** [comment]
The files where updated download latest version =)
