### ISSUE TITLE
Mila432, do you want to help with protobuf msgs?

### ISSUE THREAD

**Issue by botaifilip** [Mila432/Pokemon_Go_API#2]
![image](https://cloud.githubusercontent.com/assets/16588764/16822893/318d41aa-4960-11e6-9240-27991c5ebbbb.png)
![image](https://cloud.githubusercontent.com/assets/16588764/16822907/53f99770-4960-11e6-8972-5e3bca446f89.png)
Just a peek into our .proto files ;)

**Comment by botaifilip** [comment]
Give me your imports and i will give you contact to our chat and repository. But if you're not faking it. i can write few lines to console and screen it too

**Comment by tejado** [comment]
maybe this will help you a little bit https://github.com/tejado/pokemongo-api-demo
