### ISSUE TITLE
How to use the script? 

### ISSUE THREAD

**Issue by atgeek** [Mila432/Pokemon_Go_API#20]
The script seem very great, but you should add more info about the commands and how to use it. For example, how to obtain the Google Auth token and where past to? When I run the main.py script I receive:

[!] Using google as login..
[-] problem in google login..
[-] access_token bad

**Comment by Mila432** [comment]
@atgeek  the token is generated based on the provided login , it comes directly from google

**Comment by atgeek** [comment]
Ok so which is the file where account info must be added?

**Comment by Mila432** [comment]
@atgeek https://github.com/Mila432/Pokemon_Go_API/blob/master/logins.py

**Comment by atgeek** [comment]
I've checked all files except that. Thanks :)

**Comment by xau1** [comment]
I'm having the same issue.

[!] Using google as login..
[-] problem in google login..
[-] access_token bad


And i have only edited the logins.py file with my google logins. They are 100% correct but still getting the error.

**Comment by kkatayama** [comment]
I have logged in using your tool.  How do I load the Pokestop bot?

**Comment by xau1** [comment]
I have not logged in and don't know why it says access_token bad (this is what this topic is about)

**Comment by Mila432** [comment]
@xau1 is your problem solved?
@kkatayama the farmer code is not public yet

**Comment by xau1** [comment]
@Mila432 Yes, after an update, I think you did a small login update change with help of Nostrademous, it worked on new account too. Can you give tips for new programmers how to request the pokestops it loads on the map? I noticed it loads them all around you until a specific distance
