### ISSUE TITLE
Run to Pokestops?

### ISSUE THREAD

**Issue by Betim123** [Mila432/Pokemon_Go_API#21]
I got it work but only my stats like: Item Storage etc...

How can he farm pokestops now?
Do i need to login with my mobile phone or something or how he get the gps?

**Comment by dmadisetti** [comment]
The modules needed aren't included i.e logic, api and others. Not sure why they haven't included them yet

**Comment by AluTa49** [comment]
me too, im logged in but nothing happens

**Comment by Mila432** [comment]
the functions are working and inside logic.py , but this file private for now

**Comment by Betim123** [comment]
and why u did this public now? Didnt understood it lol

**Comment by skupfer** [comment]
He/she made it public like all of her other hacks (there is a forum) to make the public aware of it and profit later. Thats it.
