### ISSUE TITLE
TypeError: api_req() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by zelgawis2** [Mila432/Pokemon_Go_API#24]
Hey, i have problem like this. What should I do to solve it?

C:\Users\Michal\Pokemon_Go_API-master\Pokemon_Go_API-master>main.py
[!] Using google as login..
[!] using: True
[+] Token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhmYmJlZWE0...
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/301/rpc
Traceback (most recent call last):
  File "C:\Users\Michal\Pokemon_Go_API-master\Pokemon_Go_API-master\main.py", line 92, in <module>
    main()
  File "C:\Users\Michal\Pokemon_Go_API-master\Pokemon_Go_API-master\main.py", line 85, in main
    start_work(access_token,ltype)
  File "C:\Users\Michal\Pokemon_Go_API-master\Pokemon_Go_API-master\main.py", line 31, in start_work
    profile = public.get_profile(api_endpoint, access_token)
  File "C:\Users\Michal\Pokemon_Go_API-master\Pokemon_Go_API-master\public.py", line 109, in get_profile
    return api_req(api_endpoint, access_token, req.requests)
TypeError: api_req() takes exactly 4 arguments (3 given)

**Comment by Mila432** [comment]
Make sure you use the latest version

**Comment by zelgawis2** [comment]
Ok, i updated it and i can login now. But what next? Nothing happens nor in console nor in mobile phone.

**Comment by Betim123** [comment]
He dont want to publish his logic.py (pokestop farm etc.)
So its useless. have fun

**Comment by Wartoz** [comment]
yeah :/

**Comment by sadbillo** [comment]
@Betim123, you are so ingrate.
Start coding yourself a fucking own PokeStop - Farmer.

**Comment by Betim123** [comment]
@sadbillo 1. Only said the truth  2. I have already a pokestop farm 3. ingrate? The same to you

**Comment by sadbillo** [comment]
@Betim123 

We have to thank Mila that he publish a Code-Snippet for using the API of the PoGo-Servers.

PokeStop Farmer? - Keep it at this moment for yourself, @Mila432 .
