### ISSUE TITLE
errors main.py with correct logins

### ISSUE THREAD

**Issue by Wartoz** [Mila432/Pokemon_Go_API#25]
http://i.imgur.com/GTWNChC.png

how to fix this

**Comment by ThomasMW** [comment]
type 'pip install requests' in your command-prompt.

**Comment by Wartoz** [comment]
http://i.imgur.com/9fXavlP.png
got this now

**Comment by ThomasMW** [comment]
'pip install protobuf'
'pip install geopy'

**Comment by Wartoz** [comment]
now got this
http://i.imgur.com/uCF7hau.png

**Comment by Wartoz** [comment]
it cut off

**Comment by ThomasMW** [comment]
No, it works, the bot only logs in at this stage. Autofarming pokestops and catching pokemon is not yet included.

**Comment by Wartoz** [comment]
oh okey so only the owner got it working

**Comment by Wartoz** [comment]
https://www.youtube.com/watch?v=PaJHeqqC3Sw 
this thing

**Comment by ThomasMW** [comment]
Correct

**Comment by Wartoz** [comment]
okey thanks for your help appreciate it ( i'm novice )
