### ISSUE TITLE
Program doesnt change your location, write into console

### ISSUE THREAD

**Issue by wenza** [Mila432/Pokemon_Go_API#26]
Hi,
the programs by far looks like info outputing program without any real changing location, I saw some more should happen while using pokemon account not google account, but by now it looks really unuseful program. Am I wrong? Or am I missing something?
I turn on pokemon go on my android phone. Turn on the bot and nothing happens, same with usage of tejado bot, the setting location just write out lat,long,alt but doesnt really set anywhere.

**Comment by Mila432** [comment]
the functions for farming pokestops are not public yet

**Comment by phr34k0** [comment]
How can i step into development? Currently on linux. 
![screenshot from 2016-07-19 21-19-492](https://cloud.githubusercontent.com/assets/13272249/16951521/f2cab898-4df7-11e6-9014-8173f5ae7de7.png)
