### ISSUE TITLE
Porting google login

### ISSUE THREAD

**Issue by laterbreh** [Mila432/Pokemon_Go_API#27]
Hello, 

I am not sure if this is the right place to post this, but I am porting login.py starting at line 39 to a node.js equivalent. Everything is well until I get to the third url. after I post to url third, I get status code 302 with location: https://accounts.google.com/ManageAccount?authuser=0 in the header object. If i go to that url, I am unable to find the next variables that are needed for the last step. 

I have all the headers set correctly and I am able to parse all of the gxf, profile, etc. as you have in python. But posting to step third is taking me to the URL above... am I on the right track? I am getting notifications in my email that I have logged in... I am just not sure what to do next. Any information would be greatly appreciated.

**Comment by Mila432** [comment]
@laterbreh after the third url you have to extract the location inside the headers of the response 
It should do some redirects , the first one is https://accounts.google.de/accounts/SetSID?....

**Comment by laterbreh** [comment]
Okay, thank you for the response!! This will help immensely, I'm trying now to figure out how to track the redirects with the module I am using. Thank you for your help.

**Comment by Mila432** [comment]
@laterbreh tell me if you need more , by the way why this hard way and not some oauth..?

**Comment by laterbreh** [comment]
I dont believe there is a node module that will directly allow us to authenticate in the same manner that is necessary to login for the pokemon app. 

Is there any other URLS that are supposed to appear in the redirect history other than the one you linked?
