### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by samuelteixeiras** [Mila432/Pokemon_Go_API#3]
Hi, why you don't add the missing files to the github? 

How can a send a message outside github to you? (email ...)

**Comment by fremgenc** [comment]
pokemon_pb2 from https://github.com/tejado/pokemongo-api-demo/blob/master/pokemon_pb2.py

**Comment by Sritam-Mishra** [comment]
What about the Pokemon.py file?

**Comment by therealssj** [comment]
@fremgenc it's also missing the pokemon file which contains the extra methods I guess.

**Comment by KidQuid** [comment]
Yes that is missing also It is not in the repo linked above.

**Comment by Ilmatarnyymi** [comment]
Wow, why didnt you include the essential files?

**Comment by therealssj** [comment]
You can create the missing pokemon file by taking a look at this api https://github.com/tejado/pokemongo-api-demo
fairly straightforward :)

**Comment by samuelteixeiras** [comment]
Hi thanks for the answer , but I am talking with @Mila432  about the reason to not add where. 
By the way the https://github.com/tejado/pokemongo-api-demo is working for me , but @tjado get the files from here like a fork.

**Comment by Mila432** [comment]
i will clean the code stay tuned , update will be up in some hours

**Comment by PatrikChr** [comment]
Will you also add the rest of the files?

**Comment by erhan-** [comment]
I bet he will but the files are available on the other links anyway.
