### ISSUE TITLE
Login with non gmail account

### ISSUE THREAD

**Issue by dankmemes** [Mila432/Pokemon_Go_API#33]
Hello, I am having a issue when I try to login with a account that isn't a gmail account it's giving the pokemon attacking the login server access_token bad. 
I put the username/pass in the login.py file and I changed google=False is there something else I am not doing  correct?

**Comment by Mila432** [comment]
@dankmemes everything is right he problem is the login servers for ptc are offline .. I don't know if this is a bug or not , where I live it's offline for 3 days now , if it's online for you please tell me where you are from

**Comment by dankmemes** [comment]
@Mila432 West coast California.

**Comment by Mila432** [comment]
https://github.com/Mila432/Pokemon_Go_API/commit/9b846807d97a5fb4a2fd41a8a5125da2d7fd64ff
should fix this

**Comment by mew351** [comment]
Still didn't work @Mila432

**Comment by s-a-a** [comment]
@mew351 AFAIK, that's because niantic's servers are down. Their problem, not Mila's code

**Comment by Mila432** [comment]
@s-a-a i think the code had a bug , anyways the problem should be fixed with https://github.com/Mila432/Pokemon_Go_API/commit/14f1a54e7fe1a1725b0689a7421548bfe815b1c3

**Comment by s-a-a** [comment]
@Mila432 ok, if you say so, but currently I can't login into game at all. It doesn't matters what login option i choose, there is always be the "Can't login" error, or "Can't load game data" errors. So i assume it's their servers fault, not yours

**Comment by dankmemes** [comment]
@Mila432 @s-a-a During the time of the issue I was able to login to the game via my phone. Currently I am able to login via phone but I am not able to login via this for some reason. I was using the correct credentials but it told me that I had gotten one login incorrect and that I had four more attempts before being locked out for 15 minutes.

**Comment by Mila432** [comment]
@dankmemes is this problem still there ?

**Comment by dankmemes** [comment]
@Mila432 Nope! Check reddit messages tho if possible I pm'd you!
