### ISSUE TITLE
Combining efforts

### ISSUE THREAD

**Issue by rubenvereecken** [Mila432/Pokemon_Go_API#34]
I started [my own Pokemon Go API](https://github.com/rubenvereecken/pokemongo-api) repo this morning and only now encounter yours. As I've been making quite some headway I don't feel like going through the merging hassle right now. Still, looks like this one is gaining some traction and I could use a hand.

I handled some things differently: more of an object-oriented approach. The protocol is also hosted as a separate repository. The goal is to have the API be able to automate everything with really good error control. Let me know if you think this could work.

**Comment by Mila432** [comment]
@rubenvereecken sorry i am working alone
