### ISSUE TITLE
Egg Hatching

### ISSUE THREAD

**Issue by Nostrademous** [Mila432/Pokemon_Go_API#35]
I notice that "egg hatching" is not in your To-Do list. Is this not something you are interested in? I assume (but haven't recorded any flows yet) that incubating an egg sends notice to the server. 

Next, I assume client maintains distance (in km) traveled and sends a "egg hatched" message to the server. Then it's possible the server-side verifies that enough time/distance has occurred to hatch the egg before sending back the hatched Pokemon ID.

Any thoughts or flows you have for this?

**Comment by Mila432** [comment]
@Nostrademous beta farmer is hatching eggs while walking
