### ISSUE TITLE
DEBUG flag

### ISSUE THREAD

**Issue by Nostrademous** [Mila432/Pokemon_Go_API#36]
in config.py you have "debug" and "DEBUG" and in public code they are not really used. Here is a diff file with some changes.

*@*-VirtualBox: ~/Pokemon_Go_API$ git diff origin/master master

```
diff --git a/config.py b/config.py
index 244ca24..dfd6247 100644
--- a/config.py
+++ b/config.py
@@ -11,7 +11,6 @@ proxies = {
   'https': 'http://127.0.0.1:8888',
 }
 use_proxy=False
-debug=True
 
 google=True
 pub=None
@@ -32,4 +31,5 @@ SESSION.headers.update({'User-Agent': 'Niantic App'})
 if use_proxy:
        SESSION.proxies.update(proxies)
        SESSION.verify = False
-DEBUG = True
\ No newline at end of file
+
+DEBUG = False
diff --git a/main.py b/main.py
index 71800ba..0a9c29f 100644
--- a/main.py
+++ b/main.py
@@ -50,7 +50,13 @@ def main():
        parser.add_argument("-u", "--username", help="Login", required=True)
        parser.add_argument("-p", "--password", help="Password", required=True)
        parser.add_argument("-t", "--type", help="Google/PTC", required=True)
+       parser.add_argument("-d", "--debug", help="Debug Mode", action='store_true')
        args = parser.parse_args()
+       
+       if args.debug:
+               config.DEBUG = True
+               print('[!] DEBUG mode on')
+       
        if 'ptc' in args.type.lower() or 'goo' in args.type.lower():
                access_token,ltype=get_acces_token(args.username,args.password,args.type.lower())
                if access_token is not None:
```

**Comment by Nostrademous** [comment]
then we can add the following to "public.py" to actually use DEBUG for something

diff --git a/public.py b/public.py
index df94309..3bbcf5f 100644
--- a/public.py
+++ b/public.py
@@ -4,6 +4,7 @@ import struct
 import json
 import argparse
 import public_proto_pb2
+import config
 
 from datetime import datetime
 from geopy.geocoders import GoogleV3
@@ -19,7 +20,6 @@ SESSION = requests.session()
 SESSION.headers.update({'User-Agent': 'Niantic App'})
 SESSION.verify = False
 
-DEBUG = True
 COORDS_LATITUDE = 0
 COORDS_LONGITUDE = 0
 COORDS_ALTITUDE = 0
@@ -97,10 +97,17 @@ def api_req(api_endpoint, access_token, req,ltype):
 
                p_ret = public_proto_pb2.ResponseEnvelop()
                p_ret.ParseFromString(r.content)
+               
+               if config.DEBUG:
+                       print('\nRequest: ')
+                       print(p_req)
+                       print('\nResponse: ')
+                       print(p_ret)
+                       print('\n\n')
+               
                return p_ret
        except Exception,e:
-               if DEBUG:
-                       print(e)
+               print(e)
                return None

**Comment by davidmann4** [comment]
seems like you have the working code - just make a pull request
