### ISSUE TITLE
Making bot available

### ISSUE THREAD

**Issue by devian223** [Mila432/Pokemon_Go_API#41]
Not an issue, more a question.

Do you have intentions of releasing your code, or at least any sort of logic, of your bot to do the XP loop? If so, when? The reason I'm asking is because there are currently branches doing a lot more interesting stuff with the API than yours (AHAAAAAAA, marauder37), making this one rather pointless.

**Comment by Mila432** [comment]
@devian223 check the latest commit

**Comment by devian223** [comment]
Checked out your dirty.py code, impressive, well done.

I see you have added more code, like the random walking, yet as long as the logic file is not available, your commits make no sense.
