### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by ecylmz** [Mila432/Pokemon_Go_API#42]
Hi,

I try the farmer bot with your last commit(https://github.com/Mila432/Pokemon_Go_API/commit/ac6bef68f54c8c59054dff7fec0bfafa23ca7562)

These modules not in your code repository: pokemon_pb2, logic, dirty, stops, api, location. So we can not run this farmet bot. `dirty.py` and `main.py` are trying to import these modules.

**Comment by Mila432** [comment]
@ecylmz they are not public yet , the code is still being improved
location & dirty is already here
