### ISSUE TITLE
Spoof Pokemon ID

### ISSUE THREAD

**Issue by blackms** [Mila432/Pokemon_Go_API#44]
Do you think that is possible to spoof the ID of the pokemon in order to spawn a different one?

**Comment by Mila432** [comment]
you can spawn random pokemons but since the data first came from the server it wont accept the new pokemon_id

**Comment by SoNiice** [comment]
I'm not sure if I understood you right, but so it's possible to spawn a random Pokémon next to the own character but we aren't able to specify which one?

**Comment by Mila432** [comment]
@SoNiice its possible to spawn fake pokemons so in your app you will see them but they do not exist

**Comment by SoNiice** [comment]
Alright, that's what I already expected. That would be otherwise very embarrassing for Niantic.

**Comment by blackms** [comment]
If you capture it locally it should be added to your local database no?
For example: I change ID 19 to 150 (mewtwo), then in the client i see Mewtwo, once i try to capture it, can be work?

**Comment by SoNiice** [comment]
Probably not, it's still the server which sends you the pokemon ids, no matter what you edited client side.
