### ISSUE TITLE
Please, somebody helps me with the pokestop collector

### ISSUE THREAD

**Issue by josepg** [Mila432/Pokemon_Go_API#46]
I use the command to start the program, then i get (I replaced some sensible data with ***

[!] Using google as login..
[!] using: True
[+] Token: **********************...
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/***/rpc
[+] Login successful
[+] Username: ******
[+] You are playing Pokemon Go since: 2016-07-** **:**:**
[+] Poke Storage: 250
[+] Item Storage: 350
[+] POKECOIN: 80
[+] STARDUST: 16*51

And it stops there. The Youtube video shows the pokestop farmer at use, but it does not start with my version. Ty

**Comment by Mila432** [comment]
@josepg the pokestop farmer is not public yet , but the code needed for is already

**Comment by Mila432** [comment]
@josepg the pokestop farmer is not public yet , but the code needed for is already

**Comment by youngsemicolon** [comment]
@Mila432 Thanks for the reply, do you plan to make the farmer public ?
