### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by dankmemes** [Mila432/Pokemon_Go_API#49]
Hey again, not really a you issue although you may have a work around. 

" retrying_set_location: geocoder exception (The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.), retrying"

(Getting rate-limited by google map api) 
Use of the Google Geocoding API is subject to a query limit of 2,500 geolocation requests per day. [...] Additionally, we enforce a request rate limit to prevent abuse of the service.

**Comment by Mila432** [comment]
public server , if used too much you get blocked . try with vpn
