### ISSUE TITLE
Google Login failed

### ISSUE THREAD

**Issue by therealssj** [Mila432/Pokemon_Go_API#5]
I keep getting this error when I try to login.
```  
print r2.history[1].headers['Location']
IndexError: list index out of range
```

**Comment by Nostrademous** [comment]
change the [1] to [0]. Perhaps this was changed due to a recent update or it's an iOS vs Android difference.

**Comment by Mila432** [comment]
this bug is interesting but sadly i cant reproduce it. it seems more like a problem on google's side , latest commit uses a try to catch it

**Comment by Nostrademous** [comment]
Just tried this morning, currently even history[0] fails with index out of range. It's as if it doesn't exist. Sure, your try catches it, but doesn't 'fix' it.

**Comment by Nostrademous** [comment]
Changed your latest to:

        try:^M
            fourth= r2.history[1].headers['Location'].replace('amp%3B','')^M
        except:^M
            fourth= r2.history[0].headers['Location'].replace('amp%3B','')^M
            pass^M

Seems to work for me. Now we fail in api_req (will diagnose later)

VirtualBox:~/Pokemon_Go_API$ python main.py 
[!] Using google as login..
[+] Token: <TOKEN HERE>...
[-] error in api_req
[-] error in get_api_endpoint
[-] RPC server offline

**Comment by Mila432** [comment]
[-] error in api_req <- because connection timed out , i put a timeout limit
[-] error in get_api_endpoint <- because of timeout 
[-] RPC server offline <- server down ...

**Comment by Mila432** [comment]
@Nostrademous thanks https://github.com/Mila432/Pokemon_Go_API/commit/d860fdd8c2ee1b5fff9eb0cb0235426c7c34a491
