### ISSUE TITLE
i dont understand ..

### ISSUE THREAD

**Issue by mich3lam** [Mila432/Pokemon_Go_API#50]
I might be doing somerhing wronmg, but mila said that logic is implemented? all i see in my info in the console..

[+] You are playing Pokemon Go since: 2016-07-14 15:54:59
[+] Poke Storage: 250
[+] Item Storage: 350
[+] POKECOIN: 0
[+] STARDUST: 56629

thats it

**Comment by SoNiice** [comment]
Logic isn't public yet, just wait for mila to upload the clean code.

**Comment by myfirstevercode** [comment]
so even if we download it.. it wont go to poke stops? thanks for clarifying it to em. been running it smoothly except the google login which i get bad token and i thought why the program is not working like on the video ;D

**Comment by stealthhex** [comment]
Just be patient... Go outside and catch some pokemons and when you return just hope its finished xD

**Comment by mikeres0** [comment]
@stealthhex hard for us lazy trainers ;)

**Comment by stealthhex** [comment]
@mikeres0 Just download the windows spoofer then xD 

http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/562281-very-detailed-nox-pokemon-go.html

**Comment by Wartoz** [comment]
NoX / Lockito / fake GPS location / PokeGO Joystick Mod <- my equipment what do you think ? :D
