### ISSUE TITLE
Invalid URL u'https:///rpc': No host supplied

### ISSUE THREAD

**Issue by xau1** [Mila432/Pokemon_Go_API#51]
Getting this error, "no host supplied"

[!] I am a poketrainer..
[!] doing login for: ***
[!] Your given location: ***
[!] lat/long/alt: ***
[+] Token: ***...
[+] Received API endpoint: https:///rpc
Invalid URL u'https:///rpc': No host supplied
[-] Ooops...

**Comment by r00t1000** [comment]
Im getting the same error.

**Comment by Mila432** [comment]
@xau1 @r00t1000 this problem is coming from the public version 
but i can look at it

**Comment by Zenexer** [comment]
This appears to have been a result of server overload.
