### ISSUE TITLE
[WIP] Google Auth

### ISSUE THREAD

**Issue by gpires** [Mila432/Pokemon_Go_API#53]
Hello,

I couldn't login with Google so I made an alternative and more secure way to login without entering the credentials.

[auth.txt](https://github.com/Mila432/Pokemon_Go_API/files/369454/auth.txt)

**Comment by CestDiego** [comment]
What is this clientId? client_id = "848232511240-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com"
 is this something the author themself created? I feel creating an app for the sake of this shouldn't bee hardcoded like that as it would allow one user to get the tokens of many many people

**Comment by Mila432** [comment]
@CestDiego this token is hard coded from the game , but maybe differ for iOS /android

**Comment by gpires** [comment]
login_google_v2 still don't work with 2fa.
Going to try the login method of pydrive.
