### ISSUE TITLE
FYI: Good Spot to Gather Pokemons

### ISSUE THREAD

**Issue by davidmann4** [Mila432/Pokemon_Go_API#56]
lat 45.030152
lon -93.31931

![image](https://cloud.githubusercontent.com/assets/1736570/16922751/40a161d4-4d17-11e6-9c66-0e0636cadca3.png)

player movment is not necessary in this case

**Comment by Mila432** [comment]
![image](https://cloud.githubusercontent.com/assets/472947/16923334/ea25d1fc-4d19-11e6-9c7f-1d3c0cd6d30a.png)

**Comment by Nostrademous** [comment]
Nice, I need to work on sending interaction events to server next. Finally got pokemon detection done.

![poke2](https://cloud.githubusercontent.com/assets/1735956/16923410/1c15a048-4ce8-11e6-9ec3-f807e7863753.png)

**Comment by davidmann4** [comment]
@Nostrademous check out https://github.com/Grover-c13/PokeGOAPI-Java they seem more cooperative sharing informations
