### ISSUE TITLE
Login ok, and then?

### ISSUE THREAD

**Issue by crack00r** [Mila432/Pokemon_Go_API#57]
[!] Using google as login..
[!] Your given location: Washington Square, Greenwich, NY 12834, USA
[!] lat/long/alt: 43.0909305 -73.4989367 0.0
[+] Token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjY2MzkzOTBj...
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/310/rpc
[+] Login successful
[+] Username: *****
[+] You are playing Pokemon Go since: 2016-07-09 20:58:57
[+] Poke Storage: 250
[+] Item Storage: 550
[+] POKECOIN: 50
[+] STARDUST: 13534

C:\Python27>

After Login, nothing happens, how to get it working?

**Comment by Nostrademous** [comment]
Write code to make it do stuff in public.py

**Comment by crack00r** [comment]
i cant, but i´m going to donate to Mila on rls something for it

**Comment by xau1** [comment]
It's very easy. Wondering why he doesn't release it. If you don't know what to do, you can just program a small script or macro in nox, very easy. Also potentially more safe in regards to detection

**Comment by nicecodergit** [comment]
@xau1 go publish your script

**Comment by thelaw44** [comment]
@xau1 if you can tell me how do I get pokestops and how do I get items from it then I can do it :)

**Comment by Mila432** [comment]
the function is ready but not public yet
