### ISSUE TITLE
non-utf8 character

### ISSUE THREAD

**Issue by Nostrademous** [Mila432/Pokemon_Go_API#6]
The line below causes issue for me when run in linux (and won't even save in Windows using Python IDLE):

data3 = OrderedDict([('bgresponse', 'js_disabled'), ('_utf8', '☃'), ('state_wrapper', state_wrapper), ('submit_access', 'true')])

The issue is the "snowman" looking character. I replaced it with '?' and I seem to get past it, but not sure of the relevance there.

**Comment by Mila432** [comment]
Inside login.py this line should solve this problem:
# -*- coding: utf-8 -*-
('_utf8', '☃') = just shows if the request supports utf8. you can also use an "?" , this doesn't affect the other calls
