### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by zgelici** [Mila432/Pokemon_Go_API#61]
when i login it says:

[!] Using google as login..
[!] Your given location: xxxxx
[!] lat/long/alt: xxxx xxx
[+] Token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjRkODMzY2U0...
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/178/rpc
[+] Login successful
[+] Username: xxxx
[+] You are playing Pokemon Go since: 2016-07-11 21:23:42
[+] Poke Storage: 250
[+] Item Storage: 350
[+] POKECOIN: 0
[+] STARDUST: 500

params:
python main.py -u 'mygmail@gmail.com' -p 'mypw' -t 'google' -l 'New York' -d 6371

te python script stops and on my phone no reaction.

**Comment by Superdrac** [comment]
It's absolutely normal. The author didn't update his repo yet. You miss the files logic, api, stops. Which are the main files of the bot

**Comment by zgelici** [comment]
aah i was already thinking, the code in incomplete. but thanks for your answer.
