### ISSUE TITLE
About nearby pokemon location

### ISSUE THREAD

**Issue by loretoparisi** [Mila432/Pokemon_Go_API#62]
As soon as I login I get

```shell
[!] Using google as login..
[!] Your given location: Central Park, New York, NY, USA
[!] lat/long/alt: 40.7711329 -73.9741874 0.0
[+] Token: xxxxx
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/214/rpc
[+] Login successful
[+] Username: xxxx
[+] You are playing Pokemon Go since: 2016-07-17 18:34:40
[+] Poke Storage: 250
[+] Item Storage: 350
[+] POKECOIN: 0
[+] STARDUST: 100
```

but I don't get which is the location of pokemons in the nearby?

**Comment by SlinkyDinky** [comment]
Same issue here. That's using main.py?

**Comment by loretoparisi** [comment]
@SlinkyDinky yep

**Comment by Plnda** [comment]
men not everything is public yet

**Comment by xau1** [comment]
![poke](https://cloud.githubusercontent.com/assets/20493907/16929847/d67c1bc8-4d39-11e6-8eb8-b281df4555f9.jpg)

**Comment by SlinkyDinky** [comment]
My script just terminates after it gives me my account info. Do we have to have a proxy server set up?

**Comment by NoiseControllers** [comment]
@SlinkyDinky Seems to be this will be paid to have all features...

**Comment by SlinkyDinky** [comment]
@NoiseControllers Urghh. Confused. He's made this repo but not releasing all the files?

**Comment by NoiseControllers** [comment]
@SlinkyDinky You said it yourself, 
Everything points that this will not be free

**Comment by SlinkyDinky** [comment]
@NoiseControllers Damn. :-1:

**Comment by Mila432** [comment]
Everything is ready and is beta tested now , files will be released soon

**Comment by loretoparisi** [comment]
@Mila432 ok by the why here there are locations already

https://github.com/AHAAAAAAA/PokemonGo-Map

thank you!
