### ISSUE TITLE
Google Login with 2-Step Verification

### ISSUE THREAD

**Issue by ch0c01d** [Mila432/Pokemon_Go_API#64]
I'm creating simple script for who using Google Login with 2-Step Verification enabled.
First, [Generate App Password](https://security.google.com/settings/security/apppasswords?pli=1)
then login it in terminal with email and generated password from Google App Password.

[login.py.txt](https://github.com/Mila432/Pokemon_Go_API/files/370268/login.py.txt)

**Comment by OranShuster** [comment]
do we enter the password with spaces or without? i'm getting bad token on with or without spaces

**Comment by Mila432** [comment]
@OranShuster try this -p "my_S8Per*StrongPW"

**Comment by OranShuster** [comment]
you mean using brackets? i am

**Comment by theh7** [comment]
token error is indicative that the servers are having issues. try again.

**Comment by OranShuster** [comment]
if i disable my 2 factor authentication everything works fine.(and if not i get a bad token error and text msg on my phone)

**Comment by Mila432** [comment]
@OranShuster current login does not support 2fa

**Comment by OranShuster** [comment]
i saw you added a commit referencing this issues so i thought ch0c01d's code was added and works.

**Comment by Mila432** [comment]
@ch0c01d thanks for your help code added
https://github.com/Mila432/Pokemon_Go_API/commit/d4ac418cedd6f0e59c45cca1cc11c9e7fdb064fa

**Comment by ch0c01d** [comment]
your welcome :))
