### ISSUE TITLE
logic, stops, api are missing 

### ISSUE THREAD

**Issue by ziong** [Mila432/Pokemon_Go_API#68]
seems that logic, stops api files are missing...

**Comment by TonyStarkBy** [comment]
same issue

**Comment by ericlewis** [comment]
Logic, API, pokemon_pb2 are all missing. I'm working on figuring out how to recreate this.

**Comment by KyonLeague** [comment]
I think it's not supported yet...
See #26 (comment)

**Comment by ericlewis** [comment]
It is not supported yet, no. But I have a fairly decent idea of what they are doing.

**Comment by ericlewis** [comment]
It appears to mainly be based on a modified version of pokemon_pb2 for actually locating the pokemon / pokestops. As for working out the logic file itself, i will need to first reverse how they are interacting with the custom pokemon_pb2 to return a map which can be stepped through. Once I can step through the map it should be fairly simple to figure out how catch / items / pokestops work.
