### ISSUE TITLE
gps location

### ISSUE THREAD

**Issue by mich3lam** [Mila432/Pokemon_Go_API#7]
i might be too dumb but pls help me out mila. i found where to put my ptc login but where do i put the gps coordinates so it checks there? ty

**Comment by Mila432** [comment]
for the public part check this lines:
https://github.com/Mila432/Pokemon_Go_API/blob/master/public.py#L12 +2

**Comment by mich3lam** [comment]
p_req.latitude=0
p_req.longitude=0
p_req.altitude = 0

so i actually need only the first 2 right? let's say i want to use these:
-33.88595500, 151.18409300

it'll look like this?
p_req.latitude=-33.88595500
p_req.longitude=151.18409300
p_req.altitude = 0

**Comment by Mila432** [comment]
wait let me change something quickly

**Comment by Mila432** [comment]
with the latest commit set your position here
https://github.com/Mila432/Pokemon_Go_API/blob/master/public.py#L23
