### ISSUE TITLE
Missing files for catching

### ISSUE THREAD

**Issue by ahmadassaf** [Mila432/Pokemon_Go_API#77]
Hey man, great work so far. It seems that there some files missing for the `dirty` to work .. `logic` and `pokemon_pb2` are not found anywhere ? any thoughts when will you add them ?

**Comment by Staubteufel** [comment]
#26

**Comment by ahmadassaf** [comment]
doesn't this go against the purpose of Open Source and Github :) If this repo is public and you are "selling" your code to be for catching and farming added on top of an API then just publish that as an API (which there are already few of them)

**Comment by OranShuster** [comment]
i think the code is just not finished. it will be released (sold?) soon

**Comment by phr34k0** [comment]
I assume Mila is on windows. Working it out on linux. 
![screenshot from 2016-07-19 21-19-492](https://cloud.githubusercontent.com/assets/13272249/16951668/889b93ec-4df8-11e6-89da-09cca11982e8.png)

**Comment by OranShuster** [comment]
how did you start writing a bot without the api? the public only contains some location changes and that's it

**Comment by phr34k0** [comment]
PGO uses GET/POST request to RPC endpoint. I'm MiTM-ng the game on Kali. Definitely doable. Still wrapping my head around it.

**Comment by OranShuster** [comment]
so it's just double work. mila made loads of progress already

**Comment by phr34k0** [comment]
Not double. It's still is python including dependencies and multi platform capable lol. Would be easy if Mila links his part of code.

**Comment by ahmadassaf** [comment]
great stuff @phr34k0 .. would love to see where you go with it 

i believe you guys also saw https://github.com/AHAAAAAAA/PokemonGo-Map. It would be cool if this can linked with a notification service (slack, text, etc.) to notify when a not-catched pokemon is nearby

**Comment by salihozd** [comment]
@ahmadassaf it's just a fantasy for now. Just wait for release. Maybe we might have a change to develop it.

**Comment by phr34k0** [comment]
Tho i suggest @Mila432 to atleast unlist that video of his. Even tho it's open source, there be always complainers and weiners that be coming up to Niantic hence project will be for nought.
