### ISSUE TITLE
Catching Pokemon

### ISSUE THREAD

**Issue by Nostrademous** [Mila432/Pokemon_Go_API#78]
@Mila432 
Question, do you have to force an Encounter before Catching or can you straight Catch? I haven't had much luck straight catching yet.

**Comment by SlinkyDinky** [comment]
@Nostrademous Not 100% sure but I think in the video he demonstrated it. It doesn't have a cut scene. You'll see the caught Pokemon in the journal

**Comment by Nostrademous** [comment]
@SlinkyDinky perhaps, or the iPad is an emulated device he is just rendering over using Unity and didn't care to emulate fight animations. 

Regardless, I've tried issuing a direct Enounter and a direct CatchPokemon proto request and so far no dice. Perhaps the values I'm passing to them are incorrect or I'm improperly checking the distances.

I have pokestops working and was able to skip getting the descriptions (i.e., the URL image, etc.) but not capturing the pokemon yet :/

What I currently do is:

```
map_objs = getMapObjects(api_endpoint, access_token, ltype, reponse)
if not map_objs:
    break

for cell in map_objs.cells:
    for mp in cell.MapPokemon:
        catch = catchPokemon(api_endpoint, access_token, ltype, response, mp)
        if catch is not None:
            print('[+] Caught %s Pokemon' % pokemons[mp.PokedexTypeId-1]['Name'])
```

Now, I will see message that say I "caught" a pokemon, but that just means that "catch" was not "None".. which means the server replied. but when I print "catch" it's empty... so not sure what I'm doing wrong.

@Mila432 I'm using the following (where poke is a MapPokemon passed in to the function using MapPokemon protobuf)
```
        m1 = public_proto_pb2.RequestEnvelop.Requests()
        m1.type = mt.CATCH_POKEMON # 103
        m = public_proto_pb2.RequestEnvelop.CatchPokemonReq()
        m.EncounterId = poke.EncounterId
        m.SpawnPointGuid = poke.SpawnpointId
        m.Pokeball = 1
        m.HitPokemon = True
        m.SpinModifier = 0.0
        m.NormalizedReticleSize = 1.0
        m.NormalizedHitPosition = 1.0
        m1.message = m.SerializeToString()
```
anything drastically wrong there?

**Comment by Mila432** [comment]
sorry can not help you with this
