### ISSUE TITLE
Unexpected end-group tag

### ISSUE THREAD

**Issue by aleixsb** [Mila432/Pokemon_Go_API#79]
I'm getting the folowing error:

[!] Using google as login..
[!] Your given location: XXXXXX
[!] lat/long/alt: XXXXX
[+] Token: eyJhXXXXXXXXNiIsImtpZCI6IjRkODMzY2U0...
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/190/rpc
Unexpected end-group tag.
[-] Ooops...

**Comment by DavisMiculis** [comment]
Its due to server overlad, fix incoming, read comments at #31

**Comment by volksport** [comment]
@Mila432 FYI tejado patched pgoapi with a fix for the Unexpected end-group tag a few minutes ago.

**Comment by aleixsb** [comment]
thanks!
