### ISSUE TITLE
What now? again. because i needed to edit something :(

### ISSUE THREAD

**Issue by wuzziefuzzy** [Mila432/Pokemon_Go_API#84]
i tryed the bot today but when i wanted to start it i get this.
https://gyazo.com/b2433a47bd4e7d4355b6195d5a23aef0
it does nothing :(.

Do u know what the problem is?
im using NOX btw.
thx in advance.
and sry for that other isseu :(

**Comment by SlinkyDinky** [comment]
@wuzziefuzzy because he hasn't fully released it yet...

**Comment by wuzziefuzzy** [comment]
ow :D that's why sry :( i was think wow im almost there :(

**Comment by wuzziefuzzy** [comment]
pff then i go back to the fake gps :dancers:
