### ISSUE TITLE
Missing imports

### ISSUE THREAD

**Issue by aleixsb** [Mila432/Pokemon_Go_API#86]
Will you update the missing files needed in the imports?

**Comment by jppgks** [comment]
@aleixsb: `pip install -r requirements.txt`

**Comment by aleixsb** [comment]
I've done that but for example there is no logic.py

**Comment by SlinkyDinky** [comment]
@aleixsb Because he hasn't released the required files for the farming bot ect yet. Patience :+1:

**Comment by aleixsb** [comment]
ahhh ok! I thought he was because the checks in the todo list. So right now only login an tells you character info right?

**Comment by stealthhex** [comment]
Yeah its useless for several days still..
