### ISSUE TITLE
Small feature request

### ISSUE THREAD

**Issue by SlinkyDinky** [Mila432/Pokemon_Go_API#89]
I notice you've closed your thread. But I have a small idea if you can implement it. Could you add a timer for how long the bot has been running? That's if you haven't added it yet. I just think it'll be a cool feature for people who will leave bot open all night. Then we can see if there was any termination issues ect. Also ignore the hate, people aren't patient enough. I'm amazed how much time and effort you put in to this project. :+1:

**Comment by YouSaw** [comment]
There are timestamps for every action. 
https://github.com/Mila432/Pokemon_Go_API/commit/fb83f03f4236f2773d4a9b1d55b7c7f1f9c25384

And thanks

**Comment by SlinkyDinky** [comment]
@YouSaw That's awesome! :+1:
