### ISSUE TITLE
ImportError: No module named logic

### ISSUE THREAD

**Issue by abutun** [Mila432/Pokemon_Go_API#90]
Traceback (most recent call last):
  File "D:\Workspace\Pokemon\go-api\main.py", line 19, in <module>
    import logic
ImportError: No module named logic

**Comment by abutun** [comment]
Can anybody help me about this problem?

**Comment by Oxpr0x** [comment]
It's not available publicly yet.

**Comment by abutun** [comment]
OK thanks Oxpr0x :)
