### ISSUE TITLE
Where is logic.py >_<

### ISSUE THREAD

**Issue by jackrose01** [Mila432/Pokemon_Go_API#91]
hello... is there any requirements to get logic.py and another?
i want to test it and develop it...

**Comment by AnasTawfeek** [comment]
pokemon_pb2 is missing too

**Comment by jackrose01** [comment]
Keep awaiting >_<

**Comment by stealthhex** [comment]
Impatients: go here: http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/562773-c-bot-farming-pokestops-catching-pokemon.html

That works already =) but is not as good as this one...

Proof:

http://filevoid.net/rvarxG/clipboard20072016032343.png
