### ISSUE TITLE
how to use farmer/catcher?

### ISSUE THREAD

**Issue by ShiFangJuMie** [Mila432/Pokemon_Go_API#92]
`$ python main.py -u myusername -p mypassword -t Google -l 94129

[!] Using google as login..
[!] Your given location: San Francisco, CA 94129, USA
[!] lat/long/alt: 37.793323 -122.4665384 0.0
[+] Token: eyJhbGci*****************WQ3Yzgz...
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/467/rpc
[+] Login successful
[+] Username: myusername
[+] You are playing Pokemon Go since: 2016-07-09 19:18:04
[+] Poke Storage: 250
[+] Item Storage: 350
[+] POKECOIN: 0
[+] STARDUST: 75479
`

I don't know what to do next? please?

**Comment by antfuentes87** [comment]
I can't handle it! Please stop making issues about this... it has been said a 1,000 times, he has not released the logic yet. Honestly it is not that hard to create your own logic. You can clearly see how everything is working, just look at the files.

**Comment by Deradon** [comment]
@antfuentes87 What do you expect when it is listed and shown in the README.md? ;)

**Comment by antfuentes87** [comment]
@Deradon It also does state this in the README.md:

3. We are discussing the **release** but there are some problems. One point is the usage of the Pokemon GO API. We dont want Niantic to take action against API usage. There are a lot of nice projects out there built on the API. So please dont blame us about thinking about our actions.

But regardless, I just can't handle anymore emails about the same thing!!! Making me go insane!
