### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Nostrademous** [Mila432/Pokemon_Go_API#96]
@Mila432 I saw your big release and scanned through the files but I don't see the code for "capture" or "drop inventory", etc anywhere.

Are some files missing or am I just blind?

**Comment by Mila432** [comment]
"i no longer have time for this project, once i have the hype is over and nobody needs this files, do your best .. files are old backups that are working but in need of many bug fixes. should be only touched by users who know how to fix UGLY, sometimes it works ... sometimes its not :)"

this version is some old backup

**Comment by NoiseControllers** [comment]
It's all a fake

**Comment by JeremyVriens** [comment]
@Mila432 pokemon_pb2 is still missing, could you upload it as well?
